command:
  - streamlit
  - run
  - project/app_streamlit.py
  - --server.address=0.0.0.0
  - --server.port=8000

env:
  - name: PYTHONPATH
    value: .
  - name: DATABRICKS_HOST
    value_from: "{{secrets/databricks-evaluation-app/DATABRICKS_HOST}}"
  - name: DATABRICKS_OBO_TOKEN
    value_from: "{{secrets/agent-obo-scope/obo-token}}"
  - name: DATABRICKS_TOKEN
    value_from: "{{secrets/agent-obo-scope/obo-token}}"
  - name: LLM_PROVIDER
    value: databricks
  - name: DATABRICKS_MODEL_ENDPOINT
    value: databricks-meta-llama-3-3-70b-instruct
