command:
  - streamlit
  - run
  - project/app_streamlit.py
  - --server.address=0.0.0.0
  - --server.port=8000

env:
  - name: PYTHONPATH
    value: .
  - name: DATABRICKS_HOST
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: DATABRICKS_HOST
  - name: DATABRICKS_TOKEN
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: DATABRICKS_TOKEN
  - name: LLM_PROVIDER
    value: databricks
  - name: DATABRICKS_MODEL_ENDPOINT
    value: databricks-meta-llama-3-3-70b-instruct
