command:
  - streamlit
  - run
  - project/app_streamlit.py
  - --server.address=0.0.0.0
  - --server.port=8000

env:
  - name: PYTHONPATH
    value: .
  - name: DATABRICKS_HOST
    valueFrom: app-secret-databricks-host
  - name: DATABRICKS_OBO_TOKEN
    valueFrom: app-secret-obo-token
  - name: DATABRICKS_TOKEN
    valueFrom: app-secret-obo-token
  - name: LLM_PROVIDER
    value: databricks
  - name: DATABRICKS_MODEL_ENDPOINT
    value: databricks-meta-llama-3-3-70b-instruct
