command:
  - streamlit
  - run
  - project/app_streamlit.py
  - --server.address=0.0.0.0
  - --server.port=8000

env:
  - name: PYTHONPATH
    value: .
  - name: DATABRICKS_HOST
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: DATABRICKS_HOST
  - name: DATABRICKS_TOKEN
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: DATABRICKS_TOKEN
  - name: LLM_PROVIDER
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: LLM_PROVIDER
  - name: DATABRICKS_MODEL_ENDPOINT
    valueFrom:
      secretRef:
        scope: databricks-evaluation-app
        key: DATABRICKS_MODEL_ENDPOINT
